export class EditOpportunity {
    public id: string;
    public address1: string;
    public name: string;
    public lastName: string;
    public title: string;
    public organization: string;
    public status: string = "";
    public opportunityInpState: string = "";
    public currentState: string = "";
    public emailAddress: string = "";
    public phone: string = "";
    public mobilePhone: string = "";
    public fax: string = "";
    public webSite: string = "";
    public industry: string = "";
    public numberOfEmployees: string = "";
    public forecastedValue: string = "0";
    public forecastedValueCurrency: string = "";
    public leadSource: string = "";
    public city: string = "";
    public state: string = "";
    public postalCode: string = "";
    public country: string = "";
    public description: string = "";
    public tagList: string = "";
    public ownerId: string = "";
    public visiblity: string = "";
    public geo: string = "";
    public serviceLines: string = "";
    public salesType: string = "";
    public PaymentMode: string = "";
    public digitalAndInnovation: string = "";

    public businessType: string;
    public enggServiceLines: string;
    public dI_ServiceLines: string;
    public dI_Products: string;
    public UnitPrice :number;
    public Quantiy:number;
}
